[project]
name = "knowledgecollector"
version = "0.1.0"
description = "Knowledge Collector component for SmartKMS app"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv]
package = false

[tool.uv.sources]
shared = { workspace = true }
discord-collector = { workspace = true }
onedrive-collector = { workspace = true }

[tool.uv.workspace]
members = [
  "shared",
  "slack_collector",
  "discord_collector",
  "onedrive_collector",
  "api"
]

[tool.uv.build-backend]
module-root = ""

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "ruff>=0.9.9",
]